apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-frontend-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    error_log /dev/stderr info;

    http {
      resolver 8.8.8.8;
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html/browser;
        index index.html;
        server_tokens off;

        # Angular routing
        location / {
          try_files $uri $uri/ /index.html;
        }

        # API proxy
        location /api/ {
          proxy_pass https://monitoring-backend.duckdns.org;
          proxy_ssl_server_name on;
          proxy_ssl_verify off;
          proxy_set_header Host monitoring-backend.duckdns.org;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          proxy_connect_timeout 30s;
          proxy_send_timeout 30s;
          proxy_read_timeout 30s;

          # CORS headers
          add_header Access-Control-Allow-Origin * always;
          add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
          add_header Access-Control-Allow-Headers "Content-Type,Authorization" always;

          if ($request_method = 'OPTIONS') {
            add_header Content-Length 0;
            return 204;
          }
        }

        # Healthcheck
        location /health {
          return 200 "ok\n";
          add_header Content-Type text/plain;
        }
      }
    }
