apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: monitoring-frontend
          env:
            - name: ENVIRONMENT
              value: "gke"
            - name: PLATFORM
              value: "gcp"
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: monitoring-frontend-config
            items:
              - key: nginx.conf
                path: nginx.conf
      tolerations:
        - key: "cloud.google.com/gke-spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
