# overlays/gcp/patches/deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: monitoring-frontend
          env:
            - name: ENVIRONMENT
              value: "gke"
            - name: PLATFORM
              value: "gcp"
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      # Add spot instance tolerations if you want to use preemptible nodes
      tolerations:
        - key: "cloud.google.com/gke-spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"