# overlays/gcp/patches/deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      # ADD THIS: Volume for nginx config
      volumes:
      - name: nginx-config
        configMap:
          name: monitoring-frontend-config
      containers:
      - name: monitoring-frontend
        env:
        - name: ENVIRONMENT
          value: "gke"
        - name: PLATFORM
          value: "gcp"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        # ADD THIS: Volume mount for nginx config
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      # Add spot instance tolerations if you want to use preemptible nodes
      tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"