# First, include the template that defines .container_scan_base
include:
  - project: 'proxiad-academie/ops-monitoring'
    ref: experiment
    file: 'ci-templates/templates/core/.gitlab-ci-security-scanning.yml'

# Then include foundation (if needed for dependencies)
  - project: 'proxiad-academie/ops-monitoring'
    ref: experiment
    file: 'ci-templates/templates/core/.gitlab-ci-foundation.yml'

# Now you can safely extend .container_scan_base
container_scan:
  rules:
    - when: never
  
container_scan_angular:
  extends: .container_scan_base
  needs: ["docker_publish_angular"]

# Disable the original OWASP job
owasp_dependency_check:
  rules:
    - when: never

owasp_dependency_check_angular:
  extends: owasp_dependency_check
  image: maven:3.9.6-eclipse-temurin-11
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'