# Déclare les stages et les bases communes (ancres)
stages:
  - checkout
  - validate
  - build
  - security-scan
  - test
  - docker
  - docker_security
  - security-scan
  - deploy-staging
  - deploy-production
  - monitoring-verify

# Base Angular job template
.angular_base:
  image: node:18-alpine
  cache:
    key: npm-cache-$CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/
  variables:
    NODE_VERSION: "18"
    NPM_CONFIG_CACHE: "${CI_PROJECT_DIR}/.npm"
  before_script:
    - echo "Setting up Node.js environment for ${APP_NAME:-frontend}..."
    - npm config set cache $NPM_CONFIG_CACHE --global
    - node --version
    - npm --version
  tags:
    - docker



