include:
  - project: 'proxiad-academie/ops-monitoring'
    ref: experiment
    file: 'ci-templates/templates/core/.gitlab-ci-security-scanning.yml'
  - project: 'proxiad-academie/ops-monitoring'
    ref: experiment
    file: 'ci-templates/templates/core/.gitlab-ci-foundation.yml'

container_scan_angular:
  extends: .container_scan_base
  needs: ["docker_publish_angular"]

