apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-dashboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Rewrite all paths to root
    nginx.ingress.kubernetes.io/app-root: /test-pods  # Redirect root to /test-pods
spec:
  rules:
    - host: monitoring.example.com
      http:
        paths:
          - path: /test-pods
            pathType: Exact
            backend:
              service:
                name: monitoring-dashboard-service
                port:
                  number: 80
          - path: /  # Catch-all for SPA routes
            pathType: Prefix
            backend:
              service:
                name: monitoring-dashboard-service
                port:
                  number: 80