apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - production-ingress.yaml



patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patch.yaml

images:
  - name: monitoring-frontend
    newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-dashboard-ui
    newTag: latest # Replace with ${CI_COMMIT_SHORT_SHA} in GitLab CI