apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- production-ingress.yaml




images:
- name: monitoring-frontend
  newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-dashboard-ui
  newTag: 40fcbaca
patches:
- path: configmap-patch.yaml
- path: deployment-patch.yaml
