apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- production-ingress.yaml

patches:
  - target:
      kind: Deployment
      name: monitoring-frontend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: nginx-config
          mountPath: /etc/nginx/conf.d/nginx.conf
          subPath: nginx.conf
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: nginx-config
          configMap:
            name: monitoring-frontend-config
            items:
            - key: nginx.conf
              path: nginx.conf
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

images:
- name: monitoring-frontend
  newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-dashboard-ui
  newTag: 935d4b9b