apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend-service
  annotations:
    cloud.google.com/neg: '{"ingress":true}' # Enable NEG for GKE Ingress
  labels:
    app: monitoring-frontend
spec:
  selector:
    app: monitoring-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP