apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: monitoring-frontend
          resources:
            requests:
              memory: "96Mi"
              cpu: "70m"
            limits:
              memory: "192Mi"
              cpu: "150m"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: monitoring-frontend-config
            items:
              - key: nginx.conf
                path: nginx.conf
